[package]
name = "mas-installer"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "=1.3.11"
zip = "=0.6.2"

[features]
default = ["compile_static"]

compile_static = []
